# fly.toml app configuration file generated for darius-go on 2023-11-09T15:25:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "darius-go"
primary_region = "sea"

[build]

[env]
  BP_KEEP_FILES = "templates/*"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
